PKG_NAME=libschc
PKG_URL=https://github.com/imec-idlab/libschc
PKG_VERSION=c9c0d6302849ad15b74fa3d608cd4e2e0ac0484c
PKG_LICENSE=GPL-v3.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	+$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
